import type { Planet } from './types.ts';

export function getPlanetData(): Planet[] {
  return [
    {
      name: 'mercury',
      color: '#c8c8c8',
      sizeRatio: 0.383,
      distance: 0.39,
      orbitalPeriod: 87.97,
      type: 'planet',
      moons: [],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '4,879 km',
        distanceFromSun: '57.9 million km',
        orbitalPeriod: '88 days',
        numberOfMoons: 0,
        funFact: 'A day on Mercury is longer than its year.',
      },
    },
    {
      name: 'venus',
      color: '#f1c40f',
      sizeRatio: 0.949,
      distance: 0.72,
      orbitalPeriod: 224.7,
      type: 'planet',
      moons: [],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '12,104 km',
        distanceFromSun: '108.2 million km',
        orbitalPeriod: '225 days',
        numberOfMoons: 0,
        funFact: 'Venus rotates backwards compared to most planets.',
      },
    },
    {
      name: 'earth',
      color: '#3498db',
      sizeRatio: 1,
      distance: 1,
      orbitalPeriod: 365.25,
      type: 'planet',
      moons: [{ name: 'luna', distance: 30, color: '#ccc', sizeRatio: 1 }],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '12,756 km',
        distanceFromSun: '149.6 million km',
        orbitalPeriod: '365.25 days',
        numberOfMoons: 1,
        funFact: 'Earth is the only known planet to support life.',
      },
    },
    {
      name: 'mars',
      color: '#e74c3c',
      sizeRatio: 0.57,
      distance: 1.52,
      orbitalPeriod: 687,
      type: 'planet',
      moons: [
        { name: 'phobos', distance: 2.8, color: '#ccc', sizeRatio: 0.5 },
        { name: 'deimos', distance: 7, color: '#ccc', sizeRatio: 0.5 },
      ],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '6,792 km',
        distanceFromSun: '227.9 million km',
        orbitalPeriod: '687 days',
        numberOfMoons: 2,
        funFact: 'Mars has the tallest volcano in the solar system: Olympus Mons.',
      },
    },
    {
      name: 'ceres',
      color: '#a0937d',
      sizeRatio: 0.075,
      distance: 2.77,
      orbitalPeriod: 1682,
      type: 'dwarf-planet',
      moons: [],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '946 km',
        distanceFromSun: '413.7 million km',
        orbitalPeriod: '1,682 days',
        numberOfMoons: 0,
        funFact:
          "Ceres is the largest object in the asteroid belt and contains about a third of the belt's total mass.",
      },
    },
    {
      name: 'jupiter',
      color: '#f1c40f',
      sizeRatio: 2,
      distance: 5.2,
      orbitalPeriod: 4332.59,
      type: 'planet',
      moons: [
        { name: 'io', distance: 5.9, color: '#ccc', sizeRatio: 0.666 },
        { name: 'europa', distance: 9.4, color: '#ccc', sizeRatio: 0.666 },
        { name: 'ganymede', distance: 15, color: '#ccc', sizeRatio: 0.666 },
        { name: 'callisto', distance: 26.3, color: '#ccc', sizeRatio: 0.666 },
      ],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '142,984 km',
        distanceFromSun: '778.6 million km',
        orbitalPeriod: '4,333 days',
        numberOfMoons: 95,
        funFact: "Jupiter's Great Red Spot is a storm larger than Earth.",
      },
    },
    {
      name: 'saturn',
      color: '#e67e22',
      sizeRatio: 1.714,
      distance: 9.5,
      orbitalPeriod: 10759.22,
      type: 'planet',
      moons: [{ name: 'titan', distance: 20.6, color: '#ccc', sizeRatio: 1.333 }],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '120,536 km',
        distanceFromSun: '1.43 billion km',
        orbitalPeriod: '10,759 days',
        numberOfMoons: 146,
        funFact: "Saturn's rings are mostly made of ice particles.",
      },
    },
    {
      name: 'uranus',
      color: '#5da6e1',
      sizeRatio: 1.556,
      distance: 19.2,
      orbitalPeriod: 30688.5,
      type: 'planet',
      moons: [
        { name: 'titania', distance: 28.7, color: '#ccc', sizeRatio: 1 },
        { name: 'oberon', distance: 30.4, color: '#ccc', sizeRatio: 1 },
      ],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '51,118 km',
        distanceFromSun: '2.87 billion km',
        orbitalPeriod: '30,687 days',
        numberOfMoons: 28,
        funFact: 'Uranus rotates on its side with an axial tilt of 98 degrees.',
      },
    },
    {
      name: 'neptune',
      color: '#4a6f8d',
      sizeRatio: 1.556,
      distance: 30.1,
      orbitalPeriod: 60182,
      type: 'planet',
      moons: [{ name: 'triton', distance: 14.4, color: '#ccc', sizeRatio: 1 }],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '49,528 km',
        distanceFromSun: '4.5 billion km',
        orbitalPeriod: '60,190 days',
        numberOfMoons: 16,
        funFact: 'Neptune has the strongest winds in the solar system, up to 2,100 km/h.',
      },
    },
    {
      name: 'pluto',
      color: '#c4b5a0',
      sizeRatio: 0.18,
      distance: 39.5,
      orbitalPeriod: 90560,
      type: 'dwarf-planet',
      moons: [{ name: 'charon', distance: 10, color: '#9e9e9e', sizeRatio: 0.8 }],
      initialAngle: Math.random() * 2 * Math.PI,
      info: {
        diameter: '2,377 km',
        distanceFromSun: '5.9 billion km',
        orbitalPeriod: '90,560 days',
        numberOfMoons: 5,
        funFact:
          'Pluto was reclassified as a dwarf planet in 2006, but it still has a heart-shaped glacier.',
      },
    },
  ];
}
